### ISSUE TITLE
1.20.6 compat update

### ISSUE THREAD

**Issue by bruhhhwarrior** [xMystik/JoltingTrims#2]
I know this is not really an issue but i have come here to request for the plugin to be updated to 1.20.6.

This plugin (or skript addon) has been so amazing for me and my server, sadly on 1.20.6 is does not work anymore. I can get into the menu but most of the interactions do not work and trimming doesn't either.
I hope you can maybe find some time to hopefully update this, and if not, that is totally understandable.
Thank you and have a great weekend.

**Comment by xMystik** [comment]
Recently added support for versions till 1.21
